[package]
name = "xutex"
version = "0.2.1"
edition = "2024"
authors = ["Khashayar Fereidani"]
description = "an extremely fast async mutex with alternative sync API"
license = "MIT"
repository = "https://github.com/fereidani/xutex"
readme = "README.md"
keywords = ["mutex", "thread", "async", "concurrency", "lock"]
categories = ["concurrency", "asynchronous", "algorithms", "no-std"]

[workspace]
members = ["xutex-pool"]

[dependencies]
branches = "0.5"
xutex-pool = { version = "1", path = "xutex-pool" }

[dev-dependencies]
criterion = "0.7"
monoio = "0.2"
swait = "0.1"
tokio = { version = "1", features = ["full"] }
parking_lot = "0"

[[bench]]
name = "benchmark"
harness = false

[profile.release]
opt-level = 3
debug = false
overflow-checks = false
lto = 'thin'
panic = 'abort'
codegen-units = 1
rpath = false

[features]
default = ["std"]
std = []

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(loom)'] }

[target."cfg(loom)".dependencies]
loom = { version = "0.7", features = ["futures"] }
